version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    restart: "on-failure"

  web:
    build: .
    container_name: vidhya_io_api
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/shuddhi
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - redis
    restart: "on-failure"

  # pgadmin:
  #     image: dpage/pgadmin4
  #     container_name: vidhya_io_pgadmin #you can change this
  #     depends_on:
  #       - db
  #       - web
  #     ports:
  #       - "8001:80"
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #       PGADMIN_DEFAULT_PASSWORD: root
  #     restart: always
  
volumes:
  database-data: # named volumes can be managed easier using docker-compose