image:
  web:
    repository: registry.gitlab.com/ryarasi/vidhya-io-api
    tag: latest
  nginx:
    repository: nginx
    tag: latest

service:
  django:
    type: ClusterIP
    port: 8080
  nginx:
    type: LoadBalancer
    port: 80
    
resources:
  limits:
    cpu: 500m
    memory: 512mi
  requests: 
    cpu: 250m
    memory: 256mi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

