# Generated by Django 3.2.3 on 2021-08-22 14:24

from django.core.management import call_command

fixture = 'initial_data'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='vidhya') 