# Generated by Django 3.2.3 on 2021-07-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisesubmission',
            old_name='staus',
            new_name='status',
        ),
    ]
