# Generated by Django 3.2.3 on 2021-12-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterionresponse',
            name='exercise_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercisesubmission'),
            preserve_default=False,
        ),
    ]
