# Generated by Django 3.2.3 on 2021-07-29 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0002_rename_staus_exercisesubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercisefileattachment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
