# Generated by Django 3.2.3 on 2022-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0002_criterionresponse_exercise_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
