# Generated by Django 3.2.3 on 2021-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0002_auto_20210725_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
