# Generated by Django 3.2.3 on 2021-08-22 14:38
# Source - https://stackoverflow.com/a/49108587/7981162

from django.db import migrations
from django.conf import settings


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')
    domain = settings.FRONTEND_DOMAIN_URL

    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': domain}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0002_load_initial_data'),
        ('sites', '0002_alter_domain_unique'), # Required to reference `sites` in `apps.get_model()`        
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
