# Generated by Django 3.2.3 on 2021-08-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0003_update_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
