# Generated by Django 3.2.3 on 2021-08-22 14:24
# Source - https://stackoverflow.com/a/25981899/7981162

from django.core.management import call_command
from django.db import migrations
fixture = 'courses'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='vidhya') 

class Migration(migrations.Migration):  

    dependencies = [
        ('vidhya', '0003_update_site_name'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]