# Generated by Django 3.2.3 on 2021-07-26 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0003_userrole_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseFileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='exercisesubmission',
            old_name='correct_option',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='answer',
        ),
        migrations.AlterField(
            model_name='course',
            name='blurb',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='exercisesubmission',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.DeleteModel(
            name='ExerciseFileAttachments',
        ),
        migrations.AddField(
            model_name='exercisefileattachment',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercise'),
        ),
        migrations.AddField(
            model_name='exercisefileattachment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
