# Generated by Django 3.2.3 on 2021-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0003_alter_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
