# Generated by Django 3.2.3 on 2022-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0004_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='blurb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
