# Generated by Django 3.2.3 on 2021-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0004_auto_20210730_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
