# Generated by Django 3.2.3 on 2021-07-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0004_auto_20210726_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vidhya.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vidhya.institution'),
            preserve_default=False,
        ),
    ]
