# Generated by Django 3.2.3 on 2021-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
