# Generated by Django 3.2.3 on 2021-07-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0005_auto_20210730_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='due_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
