# Generated by Django 3.2.3 on 2021-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0005_auto_20210826_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
