# Generated by Django 3.2.3 on 2021-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0006_alter_institution_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
