# Generated by Django 3.2.3 on 2022-01-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0006_alter_announcement_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
