# Generated by Django 3.2.3 on 2022-03-05 09:11

import django.core.validators
from django.db import migrations, models
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0007_announcement_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', vidhya.models.LowercaseEmailField(max_length=255)),
                ('otp', models.CharField(default=vidhya.models.EmailOTP.generate_otp, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
