# Generated by Django 3.2.3 on 2021-08-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0007_auto_20210801_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseFileAttachment',
        ),
    ]
