# Generated by Django 3.2.3 on 2021-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0007_auto_20210826_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisekey',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
