# Generated by Django 3.2.3 on 2021-05-22 11:58

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0008_alter_institution_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jti',
            field=models.CharField(default=common.utils.generate_jti, editable=False, help_text='JWT tokens for the user get revoked when JWT id has regenerated.', max_length=64, verbose_name='jwt id'),
        ),
    ]
