# Generated by Django 3.2.3 on 2022-03-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0008_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
