# Generated by Django 3.2.3 on 2021-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0009_alter_exercise_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
