# Generated by Django 3.2.3 on 2021-05-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0009_user_jti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jti',
        ),
    ]
