# Generated by Django 3.2.3 on 2021-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0010_remove_user_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='searchField',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
