# Generated by Django 3.2.3 on 2022-09-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0010_auto_20220717_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
