# Generated by Django 3.2.3 on 2021-08-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0010_auto_20210827_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completedChapters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completedCourses',
        ),
        migrations.AddField(
            model_name='user',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='completedChapters', through='vidhya.CompletedChapters', to='vidhya.Chapter'),
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='completedCourses', through='vidhya.CompletedCourses', to='vidhya.Course'),
        ),
    ]
