# Generated by Django 3.2.3 on 2021-08-03 10:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0010_exercisesubmission_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_option', models.CharField(blank=True, max_length=200, null=True)),
                ('valid_answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None)),
                ('reference_link', models.CharField(blank=True, max_length=5000, null=True)),
                ('reference_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('DR', 'DRAFT'), ('CO', 'SUBMITTED'), ('GR', 'GRADED'), ('RE', 'RETURNED')], default='DR', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('searchField', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercise')),
            ],
        ),
    ]
