# Generated by Django 3.2.3 on 2022-09-10 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0011_auto_20220905_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='claps',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectClap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='clapsBy',
            field=models.ManyToManyField(blank=True, related_name='clappers', through='vidhya.ProjectClap', to=settings.AUTH_USER_MODEL),
        ),
    ]
