# Generated by Django 3.2.3 on 2021-08-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0011_exercisekey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisekey',
            old_name='valid_answer',
            new_name='valid_answers',
        ),
    ]
