# Generated by Django 3.2.3 on 2021-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0011_user_searchfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='searchField',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
