# Generated by Django 3.2.3 on 2021-08-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0012_rename_valid_answer_exercisekey_valid_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisekey',
            old_name='reference_files',
            new_name='reference_images',
        ),
        migrations.RenameField(
            model_name='exercisesubmission',
            old_name='files',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='exercisekey',
            name='searchField',
        ),
        migrations.RemoveField(
            model_name='exercisekey',
            name='status',
        ),
    ]
