# Generated by Django 3.2.3 on 2021-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0012_auto_20210827_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mandatory_prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_courses', through='vidhya.MandatoryRequiredCourses', to='vidhya.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended_prerequisites',
            field=models.ManyToManyField(blank=True, related_name='optional_courses', through='vidhya.OptionalRequiredCourses', to='vidhya.Course'),
        ),
    ]
