# Generated by Django 3.2.3 on 2022-09-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0012_auto_20220910_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects_clapped',
            field=models.ManyToManyField(blank=True, through='vidhya.ProjectClap', to='vidhya.Project'),
        ),
    ]
