# Generated by Django 3.2.3 on 2022-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0013_user_projects_clapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='claps',
            field=models.IntegerField(default=1),
        ),
    ]
