# Generated by Django 3.2.3 on 2021-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0013_auto_20210526_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
