# Generated by Django 3.2.3 on 2021-08-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0013_auto_20210827_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='prerequisites',
        ),
        migrations.AlterField(
            model_name='user',
            name='chapters',
            field=models.ManyToManyField(blank=True, through='vidhya.CompletedChapters', to='vidhya.Chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, through='vidhya.CompletedCourses', to='vidhya.Course'),
        ),
        migrations.CreateModel(
            name='MandatoryChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.chapter')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='vidhya.chapter')),
            ],
        ),
    ]
