# Generated by Django 3.2.3 on 2021-08-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0013_auto_20210803_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('PU', 'PUBLISHED')], default='DR', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('PU', 'PUBLISHED')], default='DR', max_length=2),
        ),
    ]
