# Generated by Django 3.2.3 on 2023-05-04 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0014_alter_project_claps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='courseorclass',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='institutiontype',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobileno',
            field=models.IntegerField(blank=True, default='0000000', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(blank=True, default='00000000', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='schoolorcollege',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
