# Generated by Django 3.2.3 on 2021-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0014_auto_20210827_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required', through='vidhya.MandatoryChapters', to='vidhya.Chapter'),
        ),
    ]
