# Generated by Django 3.2.3 on 2023-06-15 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0014_alter_project_claps'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(default='India', max_length=300),
        ),
        migrations.AddField(
            model_name='institution',
            name='designations',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('SC', 'School'), ('CL', 'College'), ('CO', 'Company'), ('OR', 'Organization')], default='SC', max_length=2),
        ),
        migrations.AddField(
            model_name='institution',
            name='pincode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='googleLogin',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user',
            name='manualLogin',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
