# Generated by Django 3.2.3 on 2021-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0014_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.CharField(blank=True, default='https://i.imgur.com/hB0OXas.png', max_length=250, null=True),
        ),
    ]
