# Generated by Django 3.2.3 on 2021-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0014_auto_20210805_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('PU', 'PUBLISHED'), ('AR', 'ARCHIVED')], default='DR', max_length=2),
        ),
    ]
