# Generated by Django 3.2.3 on 2023-06-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0015_auto_20230615_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
