# Generated by Django 3.2.3 on 2021-08-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0015_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='vidhya.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisekey',
            name='chapter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='vidhya.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisekey',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='vidhya.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='chapter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='vidhya.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='vidhya.course'),
            preserve_default=False,
        ),
    ]
