# Generated by Django 3.2.3 on 2021-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0015_chapter_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='index',
            field=models.IntegerField(default=100),
        ),
    ]
