# Generated by Django 3.2.3 on 2021-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0016_auto_20210808_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
