# Generated by Django 3.2.3 on 2023-07-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0016_alter_institution_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutionCoordinators', to=settings.AUTH_USER_MODEL),
        ),
    ]
