# Generated by Django 3.2.3 on 2021-08-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0017_exercisesubmission_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesubmission',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('SU', 'SUBMITTED'), ('GR', 'GRADED'), ('RE', 'RETURNED')], default='DR', max_length=2),
        ),
    ]
