# Generated by Django 3.2.3 on 2021-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0017_alter_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='searchField',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
