# Generated by Django 3.2.3 on 2023-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0018_auto_20230713_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
