# Generated by Django 3.2.3 on 2021-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0018_alter_exercisesubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesubmission',
            name='status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('SU', 'SUBMITTED'), ('GR', 'GRADED'), ('RE', 'RETURNED')], default='PE', max_length=2),
        ),
    ]
