# Generated by Django 3.2.3 on 2021-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0019_auto_20210903_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisekey',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exercisekey',
            name='reference_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
