# Generated by Django 3.2.3 on 2021-08-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0019_alter_exercisesubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesubmission',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
