# Generated by Django 3.2.3 on 2021-09-07 14:00

from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0004_load_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=vidhya.models.LowercaseEmailField(max_length=255, unique=True),
        ),
    ]
