# Generated by Django 3.2.3 on 2021-05-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0020_user_lastactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastActive',
            new_name='last_active',
        ),
    ]
