# Generated by Django 3.2.3 on 2021-08-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0020_alter_exercisesubmission_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='score',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
