# Generated by Django 3.2.3 on 2023-08-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0021_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesubmission',
            name='link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
