# Generated by Django 3.2.3 on 2021-09-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipients_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='recipients_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercisekey',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exercisekey',
            name='reference_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
