# Generated by Django 3.2.3 on 2021-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Uninitialized User', max_length=100),
        ),
    ]
