# Generated by Django 3.2.3 on 2021-09-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grader', to=settings.AUTH_USER_MODEL),
        ),
    ]
