# Generated by Django 3.2.3 on 2023-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0022_alter_exercisesubmission_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_hours',
            field=models.CharField(default='5', max_length=2),
        ),
    ]
