# Generated by Django 3.2.3 on 2021-09-18 09:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import vidhya.models

def default_rubric():
    return []


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0023_auto_20210915_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rubric',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=default_rubric),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='prompt',
            field=models.CharField(max_length=1000),
        ),
    ]
