# Generated by Django 3.2.3 on 2021-09-19 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0024_auto_20210918_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='criteriaSatisfied',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None),
        ),
    ]
