# Generated by Django 3.2.3 on 2021-09-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0025_exercisesubmission_criteriasatisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='instructions',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercisesubmission',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
