# Generated by Django 3.2.3 on 2021-09-30 11:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0026_auto_20210926_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=5000, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('PE', 'PENDING'), ('SU', 'SUBMITTED'), ('GR', 'GRADED'), ('RE', 'RETURNED')], default='PE', max_length=2)),
                ('flagged', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('criteriaSatisfied', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None)),
                ('active', models.BooleanField(default=True)),
                ('searchField', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercise')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grader_past', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
