# Generated by Django 3.2.3 on 2023-10-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0027_auto_20231011_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
