# Generated by Django 3.2.3 on 2021-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0027_submissionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionhistory',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
