# Generated by Django 3.2.3 on 2023-12-29 14:27

from django.db import migrations, models
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0028_remove_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipant',
            name='completed',
            field=models.BooleanField(default=False, verbose_name=vidhya.models.Course),
        ),
    ]
