# Generated by Django 3.2.3 on 2021-05-29 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0028_auto_20210529_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=1000)),
                ('searchField', models.CharField(blank=True, max_length=1200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.announcement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.group')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='groups',
            field=models.ManyToManyField(blank=True, through='vidhya.AnnouncementGroup', to='vidhya.Group'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vidhya.institution'),
        ),
    ]
