# Generated by Django 3.2.3 on 2021-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0028_submissionhistory_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
