# Generated by Django 3.2.3 on 2023-12-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0029_courseparticipant_completed_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseparticipant',
            old_name='completed_course',
            new_name='completed',
        ),
    ]
