# Generated by Django 3.2.3 on 2021-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0029_auto_20211010_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
