# Generated by Django 3.2.3 on 2024-06-03 10:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0029_courseparticipant_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('short_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_to_translate', models.CharField(max_length=255)),
                ('translate_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='blurb_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_blurb),
        ),
        migrations.AddField(
            model_name='course',
            name='description_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_description),
        ),
        migrations.AddField(
            model_name='course',
            name='title_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_title),
        ),
        migrations.AddField(
            model_name='project',
            name='translate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Project.default_title),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vidhya.language'),
        ),
    ]
