# Generated by Django 3.2.3 on 2024-02-13 14:38

from django.db import migrations, models
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0029_courseparticipant_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('short_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='title_object',
            field=models.JSONField(default=vidhya.models.Course.default_title),
        ),
    ]
