# Generated by Django 3.2.3 on 2024-06-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0030_auto_20240603_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.PROTECT, to='vidhya.language'),
        ),
    ]
