# Generated by Django 3.2.3 on 2024-03-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0030_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('short_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
