# Generated by Django 3.2.3 on 2021-10-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0030_alter_institution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='prompt',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='exercisesubmission',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='submissionhistory',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
