# Generated by Django 3.2.3 on 2021-06-01 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0030_auto_20210531_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
