# Generated by Django 3.2.3 on 2024-03-14 04:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0031_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blurb_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_blurb),
        ),
        migrations.AddField(
            model_name='course',
            name='description_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_description),
        ),
        migrations.AddField(
            model_name='course',
            name='title_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_title),
        ),
    ]
