# Generated by Django 3.2.3 on 2024-06-03 10:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0031_alter_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tranlate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_title),
        ),
    ]
