# Generated by Django 3.2.3 on 2021-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0031_auto_20211015_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
