# Generated by Django 3.2.3 on 2024-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0031_alter_course_title_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='En', max_length=300),
        ),
    ]
