# Generated by Django 3.2.3 on 2021-10-17 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0032_alter_announcement_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='seenBy',
        ),
        migrations.CreateModel(
            name='AnnouncementsSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='announcements',
            field=models.ManyToManyField(blank=True, through='vidhya.AnnouncementsSeen', to='vidhya.Announcement'),
        ),
    ]
