# Generated by Django 3.2.3 on 2024-03-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0032_auto_20240314_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.ForeignKey(default='en', max_length=300, on_delete=django.db.models.deletion.PROTECT, to='vidhya.language'),
        ),
    ]
