# Generated by Django 3.2.3 on 2024-06-03 10:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0032_course_tranlate'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tranlate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Announcement.default_tranlate),
        ),
        migrations.AddField(
            model_name='chapter',
            name='tranlate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Chapter.default_tranlate),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tranlate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Exercise.default_tranlate),
        ),
    ]
