# Generated by Django 3.2.3 on 2024-06-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0033_auto_20240603_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='tranlate',
            new_name='translate',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='tranlate',
            new_name='translate',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='tranlate',
            new_name='translate',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='tranlate',
            new_name='translate',
        ),
    ]
