# Generated by Django 3.2.3 on 2021-10-28 11:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import vidhya.models

def default_rubric():
    return []

class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0033_auto_20211017_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='rubric',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=default_rubric),
        ),
        migrations.AlterField(
            model_name='exercisesubmission',
            name='status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('SU', 'SUBMITTED'), ('GR', 'GRADED'), ('RE', 'RETURNED'), ('FL', 'FLAGGED')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='submissionhistory',
            name='status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('SU', 'SUBMITTED'), ('GR', 'GRADED'), ('RE', 'RETURNED'), ('FL', 'FLAGGED')], default='PE', max_length=2),
        ),
    ]
