# Generated by Django 3.2.3 on 2024-05-14 10:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0033_auto_20240313_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Project.default_title),
        ),
    ]
