# Generated by Django 3.2.3 on 2024-05-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0033_alter_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_to_translate', models.CharField(max_length=255)),
                ('translate_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
