# Generated by Django 3.2.3 on 2024-05-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0034_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='blurb_object',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_object',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_object',
        ),
    ]
