# Generated by Django 3.2.3 on 2024-05-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0034_project_title_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title_object',
            new_name='translate',
        ),
    ]
