# Generated by Django 3.2.3 on 2021-10-30 13:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0034_auto_20211028_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionhistory',
            name='rubric',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.SubmissionHistory.default_rubric),
        ),
    ]
