# Generated by Django 3.2.3 on 2021-10-31 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0035_submissionhistory_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('points', models.IntegerField()),
                ('searchField', models.CharField(blank=True, max_length=5000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('searchField', models.CharField(blank=True, max_length=5000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.criterion')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercise')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remarksBy', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
