# Generated by Django 3.2.3 on 2021-11-01 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0036_criterion_criterionresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterionresponse',
            name='grader',
        ),
        migrations.AddField(
            model_name='criterionresponse',
            name='remarker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remarker', to=settings.AUTH_USER_MODEL),
        ),
    ]
