# Generated by Django 3.2.3 on 2021-06-01 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0036_alter_institution_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitecode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('PE', 'PENDIING'), ('AP', 'APPROVED'), ('SU', 'SUSPENDED')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(default=2156975665, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
