# Generated by Django 3.2.3 on 2021-11-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0037_auto_20211101_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='exercisesubmission',
            name='criteriaSatisfied',
        ),
        migrations.RemoveField(
            model_name='exercisesubmission',
            name='rubric',
        ),
    ]
