# Generated by Django 3.2.3 on 2021-06-02 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0038_alter_institution_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(default=9799897181, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
