# Generated by Django 3.2.3 on 2021-11-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0038_auto_20211101_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invitecode',
        ),
    ]
