# Generated by Django 3.2.3 on 2021-11-16 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0039_remove_user_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisekey',
            name='valid_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='exercisesubmission',
            name='answer',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='submissionhistory',
            name='answer',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
