# Generated by Django 3.2.3 on 2021-06-02 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0039_alter_institution_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(default=9468747604, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('UI', 'UNINITIALIZED'), ('PE', 'PENDIING'), ('AP', 'APPROVED'), ('SU', 'SUSPENDED')], default='UI', max_length=2),
        ),
    ]
