# Generated by Django 3.2.3 on 2021-11-17 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0040_auto_20211116_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pass_completion_percentage',
            field=models.IntegerField(default=75, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='pass_score_percentage',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
