# Generated by Django 3.2.3 on 2021-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0041_auto_20211117_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedchapters',
            name='status',
            field=models.CharField(default='SU', max_length=2),
        ),
    ]
