# Generated by Django 3.2.3 on 2021-06-03 05:57

import django.core.validators
from django.db import migrations, models
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0043_alter_institution_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(default=vidhya.models.Institution.generate_invitecode, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
