# Generated by Django 3.2.3 on 2021-12-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0045_auto_20211129_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
