# Generated by Django 3.2.3 on 2021-06-04 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0046_auto_20210604_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='adminInChats', through='vidhya.ChatAdmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
