# Generated by Django 3.2.3 on 2021-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0048_auto_20211204_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
