# Generated by Django 3.2.3 on 2021-12-07 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0049_project_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionhistory',
            name='criteriaSatisfied',
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=2000)),
                ('resourceId', models.IntegerField(blank=True, null=True)),
                ('resourceCode', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_type', models.CharField(choices=[('US', 'USER'), ('PR', 'PROJECT'), ('IN', 'INSTITUTION'), ('SU', 'SUBMISSION'), ('CO', 'COURSE'), ('CH', 'CHAPTER')], default='US', max_length=2)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_email', vidhya.models.LowercaseEmailField(blank=True, max_length=255, null=True)),
                ('screenshot', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issueReporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
