# Generated by Django 3.2.3 on 2021-12-08 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0050_auto_20211207_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='author',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='resourceCode',
            new_name='resource_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resourceId',
        ),
        migrations.AddField(
            model_name='issue',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='searchField',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('RE', 'RESOLVED'), ('DU', 'GRADED'), ('NO', 'NO_ACTION')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
