# Generated by Django 3.2.3 on 2021-12-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0051_auto_20211208_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vidhya.institution'),
            preserve_default=False,
        ),
    ]
