# Generated by Django 3.2.3 on 2021-12-09 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0052_issue_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issueResolver', to=settings.AUTH_USER_MODEL),
        ),
    ]
