# Generated by Django 3.2.3 on 2021-06-06 08:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0052_alter_userrole_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.UserRole.default_permissions),
        ),
    ]
