# Generated by Django 3.2.3 on 2021-06-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0053_alter_userrole_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick_name',
        ),
    ]
