# Generated by Django 3.2.3 on 2021-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0054_remove_user_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
