# Generated by Django 3.2.3 on 2021-06-12 13:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0058_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sections',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.Course.default_sections),
        ),
    ]
