# Generated by Django 3.2.3 on 2021-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0059_course_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
