# Generated by Django 3.2.3 on 2021-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0060_chatmessage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('IL', 'Individual'), ('GP', 'Group')], default='IL', max_length=2),
        ),
    ]
