# Generated by Django 3.2.3 on 2021-07-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0063_auto_20210703_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vidhya.group'),
        ),
    ]
