# Generated by Django 3.2.3 on 2021-07-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0064_auto_20210703_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmember',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmember',
            name='member',
        ),
        migrations.DeleteModel(
            name='ChatAdmin',
        ),
        migrations.DeleteModel(
            name='ChatMember',
        ),
    ]
