# Generated by Django 3.2.3 on 2021-07-25 06:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0070_alter_userrole_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisefileattachments',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vidhya.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=vidhya.models.UserRole.default_permissions),
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercise')),
            ],
        ),
    ]
