# Generated by Django 3.2.3 on 2021-05-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='vidhya.institution'),
        ),
    ]
