# Generated by Django 3.2.3 on 2021-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0007_alter_institution_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
