# Generated by Django 3.2.3 on 2021-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0015_alter_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.CharField(default='https://i.imgur.com/hB0OXas.png', max_length=250),
        ),
    ]
