# Generated by Django 3.2.3 on 2021-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0018_group_searchfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='https://i.imgur.com/XDZCq2b.png', max_length=250, null=True),
        ),
    ]
