# Generated by Django 3.2.3 on 2021-05-28 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0021_rename_lastactive_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 28, 12, 16, 50, 607239, tzinfo=utc), null=True),
        ),
    ]
