# Generated by Django 3.2.3 on 2021-05-28 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0023_alter_user_last_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nick_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
