# Generated by Django 3.2.3 on 2021-05-29 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0024_auto_20210528_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, through='vidhya.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
