# Generated by Django 3.2.3 on 2021-05-29 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0026_auto_20210529_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='groupAdmins', through='vidhya.GroupAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groupMembers', through='vidhya.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
