# Generated by Django 3.2.3 on 2021-05-31 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0029_auto_20210529_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('searchField', models.CharField(
                    blank=True, max_length=1200, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='vidhya.course')),
                ('institution', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='vidhya.institution')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institutions',
            field=models.ManyToManyField(
                blank=True, through='vidhya.CourseInstitution', to='vidhya.Institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('instructions', models.CharField(max_length=1000)),
                ('searchField', models.CharField(
                    blank=True, max_length=1200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='vidhya.course')),
            ],
        ),
    ]
