# Generated by Django 3.2.3 on 2021-06-02 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0040_auto_20210602_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='invitecode',
            field=models.CharField(default=7075801397, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
