# Generated by Django 3.2.3 on 2021-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0048_auto_20210604_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
