# Generated by Django 3.2.3 on 2021-06-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0049_announcement_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.JSONField(default='{}'),
        ),
    ]
