# Generated by Django 3.2.3 on 2021-06-06 08:42

from django.db import migrations, models
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0051_alter_userrole_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.JSONField(default=vidhya.models.UserRole.default_permissions),
        ),
    ]
