# Generated by Django 3.2.3 on 2021-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0055_userrole_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='searchField',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
