# Generated by Django 3.2.3 on 2021-06-30 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0061_chat_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='individual_member_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_member_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='individual_member_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_member_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
