# Generated by Django 3.2.3 on 2021-07-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0062_auto_20210630_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.CharField(blank=True, default='https://i.imgur.com/hNdMk4c.png', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.CharField(blank=True, default='https://i.imgur.com/dPO1MlY.png', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='https://i.imgur.com/KHtECqa.png', max_length=250, null=True),
        ),
    ]
