# Generated by Django 3.2.3 on 2021-07-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0065_auto_20210703_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='group',
        ),
        migrations.DeleteModel(
            name='AnnouncementGroup',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupAdmin',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
