# Generated by Django 3.2.3 on 2021-07-24 14:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0068_auto_20210724_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=300)),
                ('question_type', models.CharField(choices=[
                 ('OP', 'OPTIONS'), ('DE', 'DESCRIPTION'), ('FL', 'FILE')], default='OP', max_length=2)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                    blank=True, max_length=200), blank=True, null=True, size=None)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='prerequisites',
            field=models.ManyToManyField(
                blank=True, related_name='required', to='vidhya.Chapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vidhya.coursesection'),
        ),
        migrations.AddField(
            model_name='course',
            name='blurb',
            field=models.CharField(default='This is a course', max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='mandatory_prerequisites',
            field=models.ManyToManyField(
                blank=True, related_name='required', to='vidhya.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended_prerequisites',
            field=models.ManyToManyField(
                blank=True, related_name='optional', to='vidhya.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExerciseFileAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[
                 ('IM', 'IMAGE'), ('DO', 'DOCUMENT'), ('ZP', 'ZIP')], default='IM', max_length=2)),
                ('exercise', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='vidhya.exercise')),
            ],
        ),
    ]
