# Generated by Django 3.2.3 on 2021-07-24 14:03

from django.db import migrations, models
import vidhya.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0069_auto_20210724_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.JSONField(default=vidhya.models.UserRole.default_permissions),
        ),
    ]
