# Generated by Django 3.2.3 on 2021-07-25 10:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0072_auto_20210725_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('instructions', models.CharField(max_length=1000)),
                ('searchField', models.CharField(
                    blank=True, max_length=1200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='vidhya.course')),
            ],
        ),
    ]
