# Generated by Django 3.2.3 on 2021-07-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidhya', '0074_auto_20210725_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='prerequisites',
        ),
    ]
