apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app
spec:
  replicas: 2
  selector:
    matchLables:
        app: app
  templates:
    metadata:
        labels:
            app: app
    spec:
        containers:
            - name: app
              image: "{{ .Values.image.django.repository }}:{{ .Values.image.django.tag }}"
              ports:
                - containerPort: 8000
              resources:
                limits:
                    cpu : {{ .Values.resources.limits.cpu }}
                    memory: {{ .Values.resources.limits.memory}}
                requests:
                    cpu: {{ .Values.resources.requests.cpu }}
                    memory: {{ .Values.resources.requests.memory}}       
              envFrom:
                - configMapRef:
                    name: my-configmap
        imagePullSecrets:
        - name: gitlab-registry
                