apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: vidhya-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"   # Correct format for CPU limit
              memory: "512Mi"  # Correct format for memory limit
            requests:
              cpu: "250m"   # Correct format for CPU request
              memory: "256Mi"  # Correct format for memory request
          envFrom:
            - configMapRef:
                name: my-configmap
      imagePullSecrets:
        - name: gitlab-registry
