apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: vidhya-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx
          configMap:
            name: nginx
      containers:
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: my-configmap 
          volumeMounts:
            - name: static-files
              mountPath: /shuddhi/staticfiles
            - name: nginx
              mountPath: /etc/nginx/conf.d
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - name: static-files
          emptyDir: {}
        - name: nginx
          configMap:
            name: nginx
