
apiVersion: apps/v1
kind: Deployment
metadata:
  maintainer: somasekharjamalla@gmail.com
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry